# Generated by Django 6.0.7 on 2026-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
