# Generated by Django 6.0.7 on 2026-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_company_user_department_user_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_UPDATE', 'Profile Update'), ('INVITATION', 'Invitation')], max_length=20),
        ),
    ]
