# Generated by Django 6.0.7 on 2026-08-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_country_user_gender_user_phone_country_code'),
        ('tenancy', '0008_alter_companymodule_company_companydeletionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenancy.company'),
        ),
    ]
