# Generated by Django 6.0.7 on 2026-09-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginactivity',
            name='login_activity_user_recent_idx',
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
