# Generated by Django 6.0.7 on 2026-09-15 13:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_current_netsuite_connection(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Preference = apps.get_model("netsuite", "NetSuiteUserConnectionPreference")

    preferences = Preference.objects.exclude(connection_id__isnull=True).values(
        "user_id",
        "connection_id",
    )

    for preference in preferences:
        User.objects.filter(
            id=preference["user_id"],
            current_netsuite_connection_id__isnull=True,
        ).update(
            current_netsuite_connection_id=preference["connection_id"],
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0012_remove_loginactivity_login_activity_user_recent_idx_and_more",
        ),
        (
            "netsuite",
            "0013_remove_netsuiteconnectionauditlog_ns_audit_user_recent_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_netsuite_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_with_current_netsuite_connection",
                to="netsuite.netsuiteconnection",
            ),
        ),
        migrations.RunPython(
            migrate_current_netsuite_connection,
            migrations.RunPython.noop,
        ),
    ]