# Generated by Django 6.0.7 on 2026-10-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_role'),
        ('ocr', '0013_alter_aiconfiguration_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_ocr_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='ocr.ocrextractiontemplate'),
        ),
    ]
