# Generated by Django 5.2.16 on 2026-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_companyplan_assigned_by_companyplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='ocr_credits',
            field=models.PositiveIntegerField(default=0, help_text='OCR documents allowed per billing cycle'),
        ),
    ]
