# Generated by Django 6.0.7 on 2026-08-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_plan_ocr_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyplan',
            name='validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
