# Generated by Django 6.0.7 on 2026-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_add_plan_price_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount'), ('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
