# Generated by Django 6.0.7 on 2026-09-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_add_transaction_discount_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='enabled_models',
        ),
    ]
