# Generated by Django 6.0.7 on 2026-09-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_remove_plan_enabled_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportSession',
        ),
    ]
