# Generated by Django 6.0.7 on 2026-09-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_delete_supportsession'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyplan',
            name='unique_active_company_plan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subscription_history',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='CompanyPlan',
        ),
    ]
