# Generated by Django 6.0.7 on 2026-09-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_companyplan_unique_active_company_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ai_credits',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_employees',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_ocr_documents',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_storage_gb',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ocr_credits',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='trial_days',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='yearly_price',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='subscription_plans',
        ),
    ]
