# Generated by Django 6.0.7 on 2026-09-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_remove_plan_ai_credits_remove_plan_max_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='final_amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount_value',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='subscription_plan_transaction',
        ),
    ]
