# Generated by Django 6.0.7 on 2026-08-05 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_alter_module_options_companymodule_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('PURCHASE', 'Purchase Report'), ('CUSTOMER', 'Customer Report'), ('VENDOR', 'Vendor Report'), ('INVENTORY', 'Inventory Report'), ('FINANCE', 'Finance Report'), ('INVOICE', 'Invoice Report'), ('OCR', 'OCR Report'), ('AI_USAGE', 'AI Usage Report'), ('NETSUITE_SYNC', 'NetSuite Sync Report')], max_length=30)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel (.xlsx)'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_engine_history',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['company', '-generated_at'], name='re_history_company_idx'), models.Index(fields=['company', 'status'], name='re_history_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('PURCHASE', 'Purchase Report'), ('CUSTOMER', 'Customer Report'), ('VENDOR', 'Vendor Report'), ('INVENTORY', 'Inventory Report'), ('FINANCE', 'Finance Report'), ('INVOICE', 'Invoice Report'), ('OCR', 'OCR Report'), ('AI_USAGE', 'AI Usage Report'), ('NETSUITE_SYNC', 'NetSuite Sync Report')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_engine_template',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='re_template_company_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('PURCHASE', 'Purchase Report'), ('CUSTOMER', 'Customer Report'), ('VENDOR', 'Vendor Report'), ('INVENTORY', 'Inventory Report'), ('FINANCE', 'Finance Report'), ('INVOICE', 'Invoice Report'), ('OCR', 'OCR Report'), ('AI_USAGE', 'AI Usage Report'), ('NETSUITE_SYNC', 'NetSuite Sync Report')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CRON', 'Custom Cron')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Future-ready custom cron.', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel (.xlsx)'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='CSV', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_engine_schedule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='re_schedule_active_idx')],
            },
        ),
    ]
