"""
WSGI config for AGSuite ERP project.

Exposes the WSGI callable as a module-level variable named `application`,
wrapped with CatalystWSGIMiddleware for Zoho Catalyst AppSail reverse proxy compatibility.
"""

import env_setup  # Automatically resolves site-packages & installs dependencies on Catalyst if needed
import os
from io import BytesIO
from django.core.wsgi import get_wsgi_application

debug = os.environ.get("DJANGO_DEBUG", os.environ.get("DEBUG", "False")).lower() in ("true", "1", "yes", "on")
default_settings = "config.settings.local" if debug else "config.settings.production"
os.environ.setdefault("DJANGO_SETTINGS_MODULE", default_settings)

_application = get_wsgi_application()


class CatalystWSGIMiddleware:
    """
    Custom Middleware for Zoho Catalyst AppSail:
    1. Fixes Chunked Transfer-Encoding / Missing Content-Length bug for POST/PUT/PATCH requests.
    2. Prevents duplicate Access-Control-Allow-Origin headers injected by both Catalyst Proxy & Django.
    """
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        # Fix 1: Read chunked payload and calculate CONTENT_LENGTH for Django
        content_length = environ.get('CONTENT_LENGTH')
        request_method = environ.get('REQUEST_METHOD', '').upper()

        if (not content_length or content_length == '0') and request_method in ('POST', 'PUT', 'PATCH'):
            try:
                input_stream = environ.get('wsgi.input')
                if input_stream:
                    body_bytes = input_stream.read()
                    environ['wsgi.input'] = BytesIO(body_bytes)
                    environ['CONTENT_LENGTH'] = str(len(body_bytes))
            except Exception as e:
                print(f"[CatalystWSGI] Failed to process payload length: {e}")

        # Fix 2: Strip duplicate CORS headers if behind Catalyst gateway
        def custom_start_response(status, headers, exc_info=None):
            # Check if running under Catalyst AppSail reverse proxy
            is_catalyst = any(k in environ for k in ('HTTP_X_ZC_ENVIRONMENT', 'HTTP_X_CATALYST_APPSPORT', 'HTTP_X_FORWARDED_FOR'))
            if is_catalyst:
                # Remove CORS headers generated by django-cors-headers to prevent duplicates
                headers = [
                    (name, val) for name, val in headers
                    if name.lower() not in ('access-control-allow-origin', 'access-control-allow-credentials')
                ]
            return start_response(status, headers, exc_info)

        return self.app(environ, custom_start_response)


application = CatalystWSGIMiddleware(_application)
