# Generated by Django 6.0.7 on 2026-09-10 12:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0012_remove_companymodule_unique_company_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=120)),
                ('record_type', models.CharField(max_length=120)),
                ('tran_id', models.CharField(max_length=80)),
                ('tran_date', models.DateField()),
                ('entity', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_products', to='tenancy.company')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-tran_date', '-id'],
                'indexes': [models.Index(fields=['company', 'transaction_type', 'record_type', 'tran_date'], name='pdt__type_record_date_idx'), models.Index(fields=['company', 'entity'], name='pdt_company_entity_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'tran_id'), name='unique_product_tran_id_company')],
            },
        ),
    ]
