# Generated by Django 6.0.7 on 2026-09-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='transaction', max_length=50)),
                ('module_code', models.CharField(blank=True, default='', max_length=80)),
                ('requires_netsuite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'navigation_transaction_menu',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='nav_tx_menu_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionMenuItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, default='transaction', max_length=50)),
                ('module_code', models.CharField(blank=True, default='', max_length=80)),
                ('requires_netsuite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.transactionmenu')),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.transactionmenuitem')),
            ],
            options={
                'db_table': 'navigation_transaction_menu_item',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['menu', 'parent_item', 'is_active', 'sort_order'], name='nav_tx_item_tree_idx'), models.Index(fields=['is_active', 'sort_order'], name='nav_tx_item_active_order_idx')],
            },
        ),
    ]
