# Generated by Django 6.0.7 on 2026-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopLevelTab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('feature_code', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dynamic_top_level_tab',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='dyn_top_tab_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicLevel2Tab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('feature_code', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_tabs', to='navigation.dynamictopleveltab')),
            ],
            options={
                'db_table': 'dynamic_level2_tab',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DynamicLevel3Tab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('feature_code', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_tabs', to='navigation.dynamiclevel2tab')),
            ],
            options={
                'db_table': 'dynamic_level3_tab',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['parent_tab', 'is_active', 'sort_order'], name='dyn_lvl3_parent_active_order_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dynamiclevel2tab',
            index=models.Index(fields=['parent_tab', 'is_active', 'sort_order'], name='dyn_lvl2_parent_active_order_idx'),
        ),
    ]
