# Generated by Django 6.0.7 on 2026-09-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_dynamictopleveltab_dynamiclevel2tab_dynamiclevel3tab_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dynamiclevel2tab',
            new_name='dyn_l2_parent_order_idx',
            old_name='dyn_lvl2_parent_active_order_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamiclevel3tab',
            new_name='dyn_l3_parent_order_idx',
            old_name='dyn_lvl3_parent_active_order_idx',
        ),
    ]
