# Generated by Django 6.0.7 on 2026-09-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_rename_dyn_lvl2_parent_active_order_idx_dyn_l2_parent_order_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationUserAccess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'navigation_user_access',
            },
        ),
        migrations.RemoveIndex(
            model_name='dynamiclevel3tab',
            name='dyn_l3_parent_order_idx',
        ),
        migrations.AddField(
            model_name='navigationuseraccess',
            name='level2_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_rows', to='navigation.dynamiclevel2tab'),
        ),
        migrations.AddField(
            model_name='navigationuseraccess',
            name='top_level_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_rows', to='navigation.dynamictopleveltab'),
        ),
        migrations.AddField(
            model_name='navigationuseraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dynamiclevel3tab',
            name='parent_tab',
        ),
        migrations.AddIndex(
            model_name='navigationuseraccess',
            index=models.Index(fields=['user', 'is_visible'], name='nav_user_access_user_vis_idx'),
        ),
        # migrations.AddConstraint(
        #     model_name='navigationuseraccess',
        #     constraint=models.CheckConstraint(condition=models.Q(models.Q(('level2_tab__isnull', True), ('level3_tab__isnull', True), ('top_level_tab__isnull', False)), models.Q(('level2_tab__isnull', False), ('level3_tab__isnull', True), ('top_level_tab__isnull', True)), models.Q(('level2_tab__isnull', True), ('level3_tab__isnull', False), ('top_level_tab__isnull', True)), _connector='OR'), name='nav_user_access_exactly_one_level'),
        # ),
        migrations.AddConstraint(
    model_name='navigationuseraccess',
    constraint=models.CheckConstraint(
        condition=models.Q(
            models.Q(
                ('level2_tab__isnull', True),
                ('top_level_tab__isnull', False),
            ),
            models.Q(
                ('level2_tab__isnull', False),
                ('top_level_tab__isnull', True),
            ),
            _connector='OR',
        ),
        name='nav_user_access_exactly_one_level',
    ),
),
        migrations.AddConstraint(
            model_name='navigationuseraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('top_level_tab__isnull', False)), fields=('user', 'top_level_tab'), name='nav_user_access_user_top_unique'),
        ),
        migrations.AddConstraint(
            model_name='navigationuseraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('level2_tab__isnull', False)), fields=('user', 'level2_tab'), name='nav_user_access_user_l2_unique'),
        ),
        # migrations.AddConstraint(
        #     model_name='navigationuseraccess',
        #     constraint=models.UniqueConstraint(condition=models.Q(('level3_tab__isnull', False)), fields=('user', 'level3_tab'), name='nav_user_access_user_l3_unique'),
        # ),
        migrations.DeleteModel(
            name='DynamicLevel3Tab',
        ),
    ]
