# Generated by Django 6.0.7 on 2026-09-07 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_navigationuseraccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='navigationuseraccess',
            name='nav_user_access_exactly_one_level',
        ),
        # migrations.RemoveConstraint(
        #     model_name='navigationuseraccess',
        #     name='nav_user_access_user_l3_unique',
        # ),
        migrations.AddConstraint(
            model_name='navigationuseraccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level2_tab__isnull', True), ('top_level_tab__isnull', False)), models.Q(('level2_tab__isnull', False), ('top_level_tab__isnull', True)), _connector='OR'), name='nav_user_access_exactly_one_level'),
        ),
    ]
