# Generated by Django 6.0.7 on 2026-09-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_navigationuseraccess_nav_user_access_exactly_one_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLevel3Tab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('feature_code', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dynamic_level3_tab',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='navigationuseraccess',
            name='nav_user_access_exactly_one_level',
        ),
        migrations.RemoveIndex(
            model_name='navigationuseraccess',
            name='nav_user_access_user_vis_idx',
        ),
        migrations.AddField(
            model_name='dynamiclevel3tab',
            name='parent_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_tabs', to='navigation.dynamiclevel2tab'),
        ),
        migrations.AddField(
            model_name='navigationuseraccess',
            name='level3_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_rows', to='navigation.dynamiclevel3tab'),
        ),
        migrations.AddConstraint(
            model_name='navigationuseraccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level2_tab__isnull', True), ('level3_tab__isnull', True), ('top_level_tab__isnull', False)), models.Q(('level2_tab__isnull', False), ('level3_tab__isnull', True), ('top_level_tab__isnull', True)), models.Q(('level2_tab__isnull', True), ('level3_tab__isnull', False), ('top_level_tab__isnull', True)), _connector='OR'), name='nav_user_access_exactly_one_level'),
        ),
        migrations.AddConstraint(
            model_name='navigationuseraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('level3_tab__isnull', False)), fields=('user', 'level3_tab'), name='nav_user_access_user_l3_unique'),
        ),
        migrations.AddIndex(
            model_name='dynamiclevel3tab',
            index=models.Index(fields=['parent_tab', 'is_active', 'sort_order'], name='dyn_l3_parent_order_idx'),
        ),
    ]
