# Generated by Django 6.0.7 on 2026-09-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_alter_dynamiclevel2tab_id_alter_dynamiclevel3tab_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiclevel2tab',
            name='feature_code',
        ),
        migrations.RemoveField(
            model_name='dynamiclevel2tab',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='dynamiclevel2tab',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='dynamiclevel3tab',
            name='feature_code',
        ),
        migrations.RemoveField(
            model_name='dynamiclevel3tab',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='dynamiclevel3tab',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='dynamictopleveltab',
            name='feature_code',
        ),
        migrations.RemoveField(
            model_name='dynamictopleveltab',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='dynamictopleveltab',
            name='query_params',
        ),
    ]
