# Generated by Django 6.0.7 on 2026-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_remove_transaction_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiclevel2tab',
            name='query_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dynamiclevel3tab',
            name='query_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dynamictopleveltab',
            name='internal_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamictopleveltab',
            name='query_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
