# Generated by Django 6.0.7 on 2026-09-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_sync_internal_id_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiclevel2tab',
            options={'ordering': ['sort_order', 'internal_id']},
        ),
        migrations.AlterModelOptions(
            name='dynamiclevel3tab',
            options={'ordering': ['sort_order', 'internal_id']},
        ),
        migrations.AlterModelOptions(
            name='dynamictopleveltab',
            options={'ordering': ['sort_order', 'internal_id']},
        ),
        migrations.AlterField(
            model_name='dynamictopleveltab',
            name='internal_id',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
