# Generated by Django 6.0.7 on 2026-09-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_remove_customize_landing_route'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dynamiclevel2tab',
            table='center_categories_table',
        ),
        migrations.AlterModelTable(
            name='dynamiclevel3tab',
            table='center_categories_subtabs_table',
        ),
        migrations.AlterModelTable(
            name='dynamictopleveltab',
            table='center_tabs_table',
        ),
    ]
