# Generated by Django 6.0.7 on 2026-09-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_alter_dynamiclevel2tab_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='navigationuseraccess',
            table='navigation_menu_path',
        ),
    ]
