# Generated by Django 6.0.7 on 2026-08-05 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_request_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('LOGISTICS', 'Logistics'), ('ECOMMERCE', 'E-commerce'), ('SERVICES', 'Professional Services'), ('OTHER', 'Other')], max_length=30)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('DEMO_COMPLETED', 'Demo Completed'), ('PROPOSAL_SENT', 'Proposal Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ONBOARDED', 'Onboarded')], default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demo_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demo_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
