# Generated by Django 6.0.7 on 2026-08-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='business_email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
