from django.urls import path

from netsuite.views import (
    NetSuiteCallbackView,
    # NetSuiteConnectView,
    NetSuiteCustomersView,
    NetSuiteEmployeesView,
    NetSuiteItemsView,
    NetSuiteVendorsView,
    NetSuiteInvoicesView,
    NetSuitePurchaseOrderView,
    NetSuiteSalesOrdersView,
    NetSuiteInvoiceDetailView,
    NetSuitePurchaseOrderDetailView,
    NetSuiteSalesOrderDetailView,
    NetSuiteItemDetailView,
    NetSuiteVendorDetailView,
    NetSuiteEmployeeDetailView,
    NetSuiteCustomerDetailView,
    NetSuiteConnectionListCreateView,
    NetSuiteConnectionDetailView,
    NetSuiteConnectionSwitchView,
    NetSuiteCompanyConnectionsView,
    NetSuiteAssignEmployeeView,
    NetSuiteRemoveEmployeeView,
    NetSuiteTestConnectionView,
    NetSuiteMyConnectionView,
)

urlpatterns = [
    # path('connect/', NetSuiteConnectView.as_view(), name='netsuite-connect'),
    path('callback/', NetSuiteCallbackView.as_view(), name='netsuite-callback'),
    path('customers/', NetSuiteCustomersView.as_view(), name='netsuite-customers'),
    path('customers/<str:record_id>/', NetSuiteCustomerDetailView.as_view(), name='netsuite-customer-detail'),
    path('employees/', NetSuiteEmployeesView.as_view(), name='netsuite-employees'),
    path('employees/<str:record_id>/', NetSuiteEmployeeDetailView.as_view(), name='netsuite-employee-detail'),
    path('vendors/', NetSuiteVendorsView.as_view(), name='netsuite-vendors'),
    path('vendors/<str:record_id>/', NetSuiteVendorDetailView.as_view(), name='netsuite-vendor-detail'),
    path('items/', NetSuiteItemsView.as_view(), name='netsuite-items'),
    path('items/<str:record_id>/', NetSuiteItemDetailView.as_view(), name='netsuite-item-detail'),
    path('sales-orders/', NetSuiteSalesOrdersView.as_view(), name='netsuite-sales-orders'),
    path('sales-orders/<str:record_id>/', NetSuiteSalesOrderDetailView.as_view(), name='netsuite-sales-order-detail'),
    path('purchase-orders/', NetSuitePurchaseOrderView.as_view(), name='netsuite-purchase-orders'),
    path('purchase-orders/<str:record_id>/', NetSuitePurchaseOrderDetailView.as_view(), name='netsuite-purchase-order-detail'),
    path('invoices/', NetSuiteInvoicesView.as_view(), name='netsuite-invoices'),
    path('invoices/<str:record_id>/', NetSuiteInvoiceDetailView.as_view(), name='netsuite-invoice-detail'),
    path("connections/",NetSuiteConnectionListCreateView.as_view(),name="netsuite_connection_list_create_view"),
    path("connections/<uuid:connection_id>/", NetSuiteConnectionDetailView.as_view(),name="netsuite_connection_detail_view"),
    path("connections/<uuid:connection_id>/switch/", NetSuiteConnectionSwitchView.as_view(),name="netsuite_connection_switch_view"),
    path("company/connections/", NetSuiteCompanyConnectionsView.as_view(), name="netsuite_company_connections"),
    path("company/connections/<uuid:connection_id>/assign-employee/", NetSuiteAssignEmployeeView.as_view(), name="netsuite_assign_employee"),
    path("company/connections/<uuid:connection_id>/remove-employee/<uuid:employee_id>/", NetSuiteRemoveEmployeeView.as_view(), name="netsuite_remove_employee"),
    path("company/connections/<uuid:connection_id>/test/", NetSuiteTestConnectionView.as_view(), name="netsuite_test_connection"),
    path("my/connection/", NetSuiteMyConnectionView.as_view(), name="netsuite_my_connection"),
]
