"""
Static baseline Vendor Bill target fields derived from the AGSuite NetSuite field workbook.

Live NetSuite metadata must override duplicate IDs at runtime. Baseline entries are
optional unless the connected account metadata marks the field required.
"""

VENDOR_BILL_BASELINE_FIELDS = [{'field_id': 'entity',
  'label': 'Customer',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Core customer on invoice'},
 {'field_id': 'tranid',
  'label': 'Invoice #',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Transaction number'},
 {'field_id': 'trandate',
  'label': 'Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Invoice date'},
 {'field_id': 'postingperiod',
  'label': 'Posting Period',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Accounting period'},
 {'field_id': 'duedate',
  'label': 'Due Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Payment due date'},
 {'field_id': 'terms',
  'label': 'Terms',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Payment terms'},
 {'field_id': 'memo',
  'label': 'Memo',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Invoice memo'},
 {'field_id': 'currency',
  'label': 'Currency',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Transaction currency'},
 {'field_id': 'exchangerate',
  'label': 'Exchange Rate',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Currency exchange rate'},
 {'field_id': 'subsidiary',
  'label': 'Subsidiary',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'OneWorld subsidiary'},
 {'field_id': 'department',
  'label': 'Department',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Department/classification'},
 {'field_id': 'class',
  'label': 'Class',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Class classification'},
 {'field_id': 'location',
  'label': 'Location',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Location'},
 {'field_id': 'salesrep',
  'label': 'Sales Rep',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Sales representative'},
 {'field_id': 'partner',
  'label': 'Partner',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Partner'},
 {'field_id': 'opportunity',
  'label': 'Opportunity',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Related opportunity'},
 {'field_id': 'createdfrom',
  'label': 'Sales Order',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Source sales order'},
 {'field_id': 'job',
  'label': 'Project / Job',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Related project/job'},
 {'field_id': 'status',
  'label': 'Status',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Invoice status'},
 {'field_id': 'approvalstatus',
  'label': 'Approval Status',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Approval status'},
 {'field_id': 'type',
  'label': 'Transaction Type',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Transaction type'},
 {'field_id': 'externalid',
  'label': 'External ID',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'External integration identifier'},
 {'field_id': 'internalid',
  'label': 'Internal ID',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'NetSuite internal identifier'},
 {'field_id': 'entityid',
  'label': 'Customer ID',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Customer identifier'},
 {'field_id': 'billaddress',
  'label': 'Billing Address',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Full billing address'},
 {'field_id': 'billaddr1',
  'label': 'Billing Address 1',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing street'},
 {'field_id': 'billaddr2',
  'label': 'Billing Address 2',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing address line 2'},
 {'field_id': 'billcity',
  'label': 'Billing City',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing city'},
 {'field_id': 'billstate',
  'label': 'Billing State',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing state'},
 {'field_id': 'billzip',
  'label': 'Billing ZIP',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing postal code'},
 {'field_id': 'billcountry',
  'label': 'Billing Country',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing country'},
 {'field_id': 'billaddressee',
  'label': 'Billing Attention',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing addressee'},
 {'field_id': 'billphone',
  'label': 'Billing Phone',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billing phone'},
 {'field_id': 'shipaddress',
  'label': 'Shipping Address',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Full shipping address'},
 {'field_id': 'shipaddr1',
  'label': 'Shipping Address 1',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping street'},
 {'field_id': 'shipaddr2',
  'label': 'Shipping Address 2',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping address line 2'},
 {'field_id': 'shipcity',
  'label': 'Shipping City',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping city'},
 {'field_id': 'shipstate',
  'label': 'Shipping State',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping state'},
 {'field_id': 'shipzip',
  'label': 'Shipping ZIP',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping postal code'},
 {'field_id': 'shipcountry',
  'label': 'Shipping Country',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping country'},
 {'field_id': 'shipaddressee',
  'label': 'Shipping Attention',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping addressee'},
 {'field_id': 'shipphone',
  'label': 'Shipping Phone',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping phone'},
 {'field_id': 'account',
  'label': 'Account / A/R Account (account)',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Receivables/account field; exact use depends on setup'},
 {'field_id': 'aracct',
  'label': 'Account / A/R Account (aracct)',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Receivables/account field; exact use depends on setup'},
 {'field_id': 'taxperiod',
  'label': 'Tax Period',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax period'},
 {'field_id': 'taxpointdate',
  'label': 'Tax Point Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax point date where enabled'},
 {'field_id': 'revrecschedule',
  'label': 'Revenue Recognition Rule',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition schedule'},
 {'field_id': 'revrecschedule',
  'label': 'Revenue Recognition Rule',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition schedule'},
 {'field_id': 'startdate',
  'label': 'Revenue Recognition Start Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition start'},
 {'field_id': 'startdate',
  'label': 'Revenue Recognition Start Date',
  'datatype': 'date',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition start'},
 {'field_id': 'enddate',
  'label': 'Revenue Recognition End Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition end'},
 {'field_id': 'enddate',
  'label': 'Revenue Recognition End Date',
  'datatype': 'date',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Revenue recognition end'},
 {'field_id': 'item',
  'label': 'Item',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Item/service being invoiced'},
 {'field_id': 'description',
  'label': 'Description',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line description'},
 {'field_id': 'quantity',
  'label': 'Quantity',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Quantity invoiced'},
 {'field_id': 'units',
  'label': 'Units',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Units of measure'},
 {'field_id': 'rate',
  'label': 'Rate',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Unit rate'},
 {'field_id': 'amount',
  'label': 'Amount',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line amount'},
 {'field_id': 'taxcode',
  'label': 'Tax Code',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax code'},
 {'field_id': 'taxrate1',
  'label': 'Tax Rate',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax rate'},
 {'field_id': 'tax1amt',
  'label': 'Tax Amount',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line tax amount'},
 {'field_id': 'grossamt',
  'label': 'Gross Amount',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Gross line amount'},
 {'field_id': 'location',
  'label': 'Location',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line location'},
 {'field_id': 'department',
  'label': 'Department',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line department'},
 {'field_id': 'class',
  'label': 'Class',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line class'},
 {'field_id': 'inventorydetail',
  'label': 'Inventory Detail',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Lot/serial/bin inventory details'},
 {'field_id': 'isbillable',
  'label': 'Billable',
  'datatype': 'boolean',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Billable indicator'},
 {'field_id': 'isclosed',
  'label': 'Closed',
  'datatype': 'boolean',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line closed status'},
 {'field_id': 'revrecstartdate',
  'label': 'Revenue Recognition Start',
  'datatype': 'date',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line rev-rec start'},
 {'field_id': 'revrecenddate',
  'label': 'Revenue Recognition End',
  'datatype': 'date',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Line rev-rec end'},
 {'field_id': 'amortizationsched',
  'label': 'Amortization Schedule',
  'datatype': 'text',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Amortization schedule'},
 {'field_id': 'taxtotal',
  'label': 'Tax Total',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Invoice tax total'},
 {'field_id': 'taxregistration',
  'label': 'Tax Registration Number (taxregistration)',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax registration; exact field depends on configuration'},
 {'field_id': 'taxregnum',
  'label': 'Tax Registration Number (taxregnum)',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax registration; exact field depends on configuration'},
 {'field_id': 'taxdetails',
  'label': 'Tax Details',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax details subrecord/feature'},
 {'field_id': 'taxdetailsreference',
  'label': 'Tax Details Reference',
  'datatype': 'number',
  'scope': 'line',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax detail reference'},
 {'field_id': 'nexus',
  'label': 'Tax Nexus',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Tax nexus'},
 {'field_id': 'shipdate',
  'label': 'Ship Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping date'},
 {'field_id': 'shipmethod',
  'label': 'Ship Via',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping method'},
 {'field_id': 'shippingcost',
  'label': 'Shipping Cost',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping charge'},
 {'field_id': 'shippingtax1rate',
  'label': 'Shipping Tax',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping tax rate/related tax fields'},
 {'field_id': 'shipcarrier',
  'label': 'Shipping Carrier',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Shipping carrier'},
 {'field_id': 'fob',
  'label': 'FOB',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Freight terms where enabled'},
 {'field_id': 'handlingcost',
  'label': 'Handling Cost',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Handling charge'},
 {'field_id': 'linkedtrackingnumbers',
  'label': 'Tracking Number',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Linked tracking numbers'},
 {'field_id': 'paymentmethod',
  'label': 'Payment Method',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Payment method'},
 {'field_id': 'deposit',
  'label': 'Deposit',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Deposit/payment reference where applicable'},
 {'field_id': 'amountpaid',
  'label': 'Amount Paid',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Amount paid'},
 {'field_id': 'amountremaining',
  'label': 'Amount Remaining',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Outstanding balance'},
 {'field_id': 'subtotal',
  'label': 'Subtotal',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Subtotal before tax/other charges'},
 {'field_id': 'discounttotal',
  'label': 'Discount',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Discount total'},
 {'field_id': 'total',
  'label': 'Total',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Invoice total'},
 {'field_id': 'fxamount',
  'label': 'Foreign Currency Total',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Foreign currency amount'},
 {'field_id': 'fxamountpaid',
  'label': 'Foreign Currency Amount Paid',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Paid amount in foreign currency'},
 {'field_id': 'fxamountremaining',
  'label': 'Foreign Currency Amount Remaining',
  'datatype': 'number',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Remaining amount in foreign currency'},
 {'field_id': 'email',
  'label': 'Email',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Customer email'},
 {'field_id': 'tobeemailed',
  'label': 'To Be Emailed',
  'datatype': 'boolean',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Email invoice flag'},
 {'field_id': 'message',
  'label': 'Email Message',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Email/message text'},
 {'field_id': 'emailtemplate',
  'label': 'Email Template',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Email template'},
 {'field_id': 'tobeprinted',
  'label': 'To Be Printed',
  'datatype': 'boolean',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Print invoice flag'},
 {'field_id': 'createddate',
  'label': 'Created Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Creation timestamp'},
 {'field_id': 'lastmodifieddate',
  'label': 'Last Modified Date',
  'datatype': 'date',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Last modification timestamp'},
 {'field_id': 'createdby',
  'label': 'Created By',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'User who created record'},
 {'field_id': 'lastmodifiedby',
  'label': 'Last Modified By',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Last modifying user'},
 {'field_id': 'recordtype',
  'label': 'Record Type',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Record type'},
 {'field_id': 'source',
  'label': 'Source',
  'datatype': 'text',
  'scope': 'body',
  'is_required': False,
  'is_custom': False,
  'reference_type': None,
  'baseline': True,
  'description': 'Transaction source'}]
