# Generated by Django 6.0.7 on 2026-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='traceback',
            field=models.TextField(blank=True),
        ),
    ]
