# Generated by Django 6.0.7 on 2026-07-23 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netsuite', '0005_netsuiteconnection_last_used_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='netsuite.netsuiteconnection')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sync.syncrun')),
            ],
            options={
                'db_table': 'sync_stage',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['connection', '-created_at'], name='sync_run_connection_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncstage',
            constraint=models.UniqueConstraint(fields=('run', 'record_type'), name='unique_run_record_type'),
        ),
    ]
