# Generated by Django 6.0.7 on 2026-07-23 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=20, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ai.aiconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_audit_user_recent_idx')],
            },
        ),
    ]
