# Generated by Django 6.0.7 on 2026-09-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_role_company_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
