# Generated by Django 6.0.7 on 2026-09-08 11:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0011_add_company_industry_size_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=120)),
                ('record_type', models.CharField(max_length=120)),
                ('tran_id', models.CharField(max_length=80)),
                ('tran_date', models.DateField()),
                ('entity', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_transactions', to='tenancy.company')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-tran_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('item_external_id', models.CharField(blank=True, default='', max_length=80)),
                ('item_sku', models.CharField(blank=True, default='', max_length=120)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_line',
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'transaction_type', 'record_type', 'tran_date'], name='tx__type_record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'entity'], name='tx_company_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('company', 'tran_id'), name='unique_transaction_tran_id_company'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['transaction', 'line_number'], name='tx_line_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionline',
            constraint=models.UniqueConstraint(fields=('transaction', 'line_number'), name='unique_transaction_line_number'),
        ),
    ]
