# Generated by Django 6.0.7 on 2026-09-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionline',
            name='tx_line_parent_idx',
        ),
        migrations.RemoveConstraint(
            model_name='transactionline',
            name='unique_transaction_line_number',
        ),
        migrations.DeleteModel(
            name='TransactionLine',
        ),
    ]
