# Generated by Django 6.0.7 on 2026-08-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('sync', 'Sync'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('upload', 'Upload'), ('review', 'Review'), ('chat', 'Chat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('company', 'Company'), ('employee', 'Employee'), ('ocr', 'OCR'), ('ai', 'AI'), ('reports', 'Reports'), ('dashboard', 'Dashboard'), ('netsuite', 'NetSuite'), ('settings', 'Settings'), ('rbac', 'RBAC'), ('auth', 'Authentication')], max_length=50),
        ),
    ]
