# Generated by Django 5.2.16 on 2026-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action_alter_auditlog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('sync', 'Sync'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('upload', 'Upload'), ('review', 'Review'), ('chat', 'Chat'), ('assign', 'Assign'), ('approve', 'Approve'), ('reject', 'Reject'), ('send', 'Send'), ('accept', 'Accept')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('company', 'Company'), ('employee', 'Employee'), ('ocr', 'OCR'), ('ai', 'AI'), ('reports', 'Reports'), ('dashboard', 'Dashboard'), ('netsuite', 'NetSuite'), ('settings', 'Settings'), ('rbac', 'RBAC'), ('auth', 'Authentication'), ('demo', 'Demo Request'), ('invitation', 'Invitation'), ('subscription', 'Subscription'), ('invoice', 'Invoice')], max_length=50),
        ),
    ]
