# Generated by Django 6.0.7 on 2026-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action_alter_auditlog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('company', 'Company'), ('employee', 'Employee'), ('invoice', 'Invoice'), ('ocr', 'OCR'), ('ai', 'AI'), ('reports', 'Reports'), ('dashboard', 'Dashboard'), ('netsuite', 'NetSuite'), ('settings', 'Settings'), ('rbac', 'RBAC'), ('auth', 'Authentication'), ('demo', 'Demo Request'), ('invitation', 'Invitation'), ('subscription', 'Subscription')], max_length=50),
        ),
    ]
