# Generated by Django 6.0.7 on 2026-07-31 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ocr/')),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('file_hash', models.CharField(help_text='SHA256 hash of the file content for duplicate detection.', max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_session', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_upload',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ocr_upload_user_recent_idx'), models.Index(fields=['file_hash'], name='ocr_upload_file_hash_idx'), models.Index(fields=['status'], name='ocr_upload_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='ocr_upload_file_size_non_negative')],
            },
        ),
    ]
