# Generated by Django 6.0.7 on 2026-08-05 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
        ('tenancy', '0004_alter_module_options_companymodule_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SALES_ORDER', 'Sales Order'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('RECEIPT', 'Receipt'), ('DELIVERY_CHALLAN', 'Delivery Challan'), ('PACKING_LIST', 'Packing List'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=40)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('CLASSIFYING', 'Classifying'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('READY_FOR_NETSUITE', 'Ready for NetSuite'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=30)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('processing_metadata', models.JSONField(blank=True, default=dict, help_text='Pipeline state: current_stage, retry_count, and stage timeline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to='tenancy.company')),
                ('upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ocr.ocrupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRDocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('page_image', models.FileField(blank=True, null=True, upload_to='ocr/pages/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('layout_blocks', models.JSONField(blank=True, default=dict)),
                ('is_blank', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.ocrdocument')),
            ],
            options={
                'db_table': 'ocr_document_page',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='OCRDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('original_document', models.FileField(blank=True, null=True, upload_to='ocr/versions/original/')),
                ('processed_document', models.FileField(blank=True, null=True, upload_to='ocr/versions/processed/')),
                ('raw_ocr', models.JSONField(blank=True, default=dict)),
                ('normalized_json', models.JSONField(blank=True, default=dict)),
                ('reviewed_json', models.JSONField(blank=True, default=dict)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ocr.ocrdocument')),
            ],
            options={
                'db_table': 'ocr_document_version',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='OCRQualityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='UNKNOWN', max_length=40)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('validation_failures', models.PositiveIntegerField(default=0)),
                ('ocr_accuracy', models.FloatField(default=0.0)),
                ('extraction_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_quality_metrics', to='tenancy.company')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='ocr.ocrupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_quality_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_quality_metric',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ocrdocument',
            index=models.Index(fields=['user', '-created_at'], name='ocr_doc_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrdocument',
            index=models.Index(fields=['company', '-created_at'], name='ocr_doc_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrdocument',
            index=models.Index(fields=['status'], name='ocr_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrdocument',
            index=models.Index(fields=['document_type'], name='ocr_doc_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrdocumentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='unique_document_page_number'),
        ),
        migrations.AddConstraint(
            model_name='ocrdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version'),
        ),
        migrations.AddIndex(
            model_name='ocrqualitymetric',
            index=models.Index(fields=['user', '-created_at'], name='ocr_qm_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrqualitymetric',
            index=models.Index(fields=['company', '-created_at'], name='ocr_qm_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrqualitymetric',
            index=models.Index(fields=['document_type'], name='ocr_qm_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrqualitymetric',
            index=models.Index(fields=['success'], name='ocr_qm_success_idx'),
        ),
    ]
