# Generated by Django 6.0.7 on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrdocument_ocrdocumentpage_ocrdocumentversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrupload',
            old_name='failure_session',
            new_name='failure_reason',
        ),
    ]
