# Generated by Django 6.0.7 on 2026-08-13 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_rename_failure_session_ocrupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='currency',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='subsidiary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocumentversion',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OCRLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ocr.ocrdocumentversion')),
            ],
            options={
                'db_table': 'ocr_line_item',
                'ordering': ['line_number'],
                'indexes': [models.Index(fields=['version', 'line_number'], name='ocr_line_item_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'line_number'), name='unique_ocr_line_item_number')],
            },
        ),
    ]
