# Generated by Django 6.0.7 on 2026-08-13 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_ocrdocumentversion_currency_and_more'),
        ('tenancy', '0005_companymodule_last_usage_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('DIRECT', 'Direct Upload'), ('ZIP', 'ZIP Archive')], default='DIRECT', max_length=20)),
                ('original_filename', models.CharField(blank=True, help_text='Original ZIP filename when source_type=ZIP.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='ocr.ocrbatch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_batches', to='tenancy.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_batch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ocr_batch_user_recent_idx'), models.Index(fields=['company', '-created_at'], name='ocr_batch_company_recent_idx'), models.Index(fields=['status'], name='ocr_batch_status_idx')],
            },
        ),
    ]
