# Generated by Django 6.0.7 on 2026-08-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_ocrbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrbatch',
            name='batch',
        ),
        migrations.AddField(
            model_name='ocrupload',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='ocr.ocrbatch'),
        ),
    ]
