# Generated by Django 6.0.7 on 2026-08-20 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_remove_ocrbatch_batch_ocrupload_batch'),
        ('tenancy', '0011_add_company_industry_size_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrbatch',
            name='requested_fields_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='OCRExtractionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('fields_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_extraction_templates', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_extraction_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_extraction_template',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'name'], name='ocr_tmpl_company_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_ocr_extraction_template_name_per_company')],
            },
        ),
    ]
