# Generated by Django 6.0.7 on 2026-08-21 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0009_add_field_mapping_validation_models'),
        ('ocr', '0007_ocrbatch_requested_fields_json_ocrextractiontemplate'),
        ('tenancy', '0011_add_company_industry_size_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRNetSuiteFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(default='vendorBill', max_length=80)),
                ('source_field_key', models.CharField(max_length=100)),
                ('source_field_label', models.CharField(max_length=255)),
                ('source_scope', models.CharField(choices=[('header', 'Header'), ('line', 'Line Item')], max_length=20)),
                ('source_datatype', models.CharField(max_length=20)),
                ('target_field_id', models.CharField(max_length=100)),
                ('target_field_label', models.CharField(max_length=255)),
                ('target_scope', models.CharField(max_length=20)),
                ('target_datatype', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('reference_type', models.CharField(blank=True, max_length=80, null=True)),
                ('mapping_status', models.CharField(choices=[('MAPPED', 'Mapped'), ('AMBIGUOUS', 'Ambiguous'), ('UNRESOLVED', 'Unresolved'), ('INCOMPATIBLE', 'Incompatible')], default='MAPPED', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_netsuite_field_mappings', to='tenancy.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_field_mappings', to='netsuite.netsuiteconnection')),
            ],
            options={
                'db_table': 'ocr_netsuite_field_mapping',
                'ordering': ['source_field_key'],
                'indexes': [models.Index(fields=['company', 'connection', 'record_type'], name='ocr_ns_map_conn_idx'), models.Index(fields=['source_field_key'], name='ocr_ns_map_src_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'connection', 'record_type', 'source_field_key'), name='unique_ocr_netsuite_mapping_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='OCRValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('PARTIAL', 'Partial')], default='VALIDATION_FAILED', max_length=20)),
                ('vendor_extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_matched', models.BooleanField(default=False)),
                ('vendor_netsuite_id', models.CharField(blank=True, max_length=64, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_validation_results', to='netsuite.netsuiteconnection')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='ocr.ocrdocument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='ocr.ocrdocumentversion')),
            ],
            options={
                'db_table': 'ocr_validation_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'version'], name='ocr_val_doc_ver_idx'), models.Index(fields=['connection', 'status'], name='ocr_val_conn_status_idx')],
            },
        ),
    ]
