# Generated by Django 6.0.7 on 2026-09-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_add_field_mapping_validation_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ocrdocumentpage',
            name='unique_document_page_number',
        ),
        migrations.RemoveIndex(
            model_name='ocrqualitymetric',
            name='ocr_qm_user_recent_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrqualitymetric',
            name='ocr_qm_company_recent_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrqualitymetric',
            name='ocr_qm_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrqualitymetric',
            name='ocr_qm_success_idx',
        ),
        migrations.RemoveField(
            model_name='ocrqualitymetric',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ocrqualitymetric',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='ocrqualitymetric',
            name='user',
        ),
        migrations.DeleteModel(
            name='OCRDocumentPage',
        ),
        migrations.DeleteModel(
            name='OCRQualityMetric',
        ),
    ]
