# Generated by Django 6.0.7 on 2026-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_remove_ocrdocumentpage_unique_document_page_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ocrlineitem',
            name='ocr_line_item_version_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ocrlineitem',
            name='unique_ocr_line_item_number',
        ),
        migrations.DeleteModel(
            name='OCRLineItem',
        ),
    ]
