# Generated by Django 6.0.7 on 2026-09-23 12:13

import common.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_ocrbatch_processing_mode_and_ocrupload_live_result'),
        ('tenancy', '0015_company_plan_company_plan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=20)),
                ('model', models.CharField(max_length=150)),
                ('api_key', common.crypto.EncryptedTextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_ai_configuration', to='tenancy.company')),
            ],
            options={
                'db_table': 'ocr_ai_configuration',
            },
        ),
    ]
