# Generated by Django 6.0.7 on 2026-09-29 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_aiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=50)),
                ('provider_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_provider_model',
                'indexes': [models.Index(fields=['provider_key', 'is_active'], name='ai_provider_model_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_key', 'model_id'), name='ai_provider_model_unique')],
            },
        ),
    ]
