# Generated by Django 6.0.7 on 2026-07-17 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuiteconnection',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='environment',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='netsuiteconnection',
            constraint=models.UniqueConstraint(fields=('user', 'netsuite_account_id'), name='unique_user_netsuite_account'),
        ),
    ]
