# Generated by Django 6.0.7 on 2026-07-20 05:55

import common.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0002_netsuiteconnection_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='access_token',
            field=common.utils.crypto.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='client_secret',
            field=common.utils.crypto.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='refresh_token',
            field=common.utils.crypto.EncryptedTextField(blank=True, null=True),
        ),
    ]
