# Generated by Django 6.0.7 on 2026-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0003_alter_netsuiteconnection_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuiteconnection',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
