# Generated by Django 6.0.7 on 2026-07-23 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0004_netsuiteconnection_consecutive_failures_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuiteconnection',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time any live NetSuite API call succeeded through this connection — broader than last_synced_at, which is scoped to sync jobs specifically.', null=True),
        ),
        migrations.CreateModel(
            name='NetSuiteConnectionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('oauth_completed', 'OAuth Completed'), ('renamed', 'Renamed'), ('switched_active', 'Switched Active'), ('deleted', 'Deleted'), ('sync_failed', 'Sync Failed')], max_length=30)),
                ('netsuite_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='netsuite.netsuiteconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsuite_connection_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'netsuite_connection_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ns_audit_user_recent_idx')],
            },
        ),
    ]
