# Generated by Django 6.0.7 on 2026-07-27 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0005_netsuiteconnection_last_used_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='netsuiteconnection',
            index=models.Index(fields=['user', 'is_active'], name='netsuite_conn_user_active_idx'),
        ),
    ]
