# Generated by Django 5.2.16 on 2026-08-06 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0006_netsuiteconnection_netsuite_conn_user_active_idx'),
        ('tenancy', '0005_companymodule_last_usage_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_netsuite_connection',
            },
        ),
        migrations.AddField(
            model_name='netsuiteconnection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_connections', to='tenancy.company'),
        ),
        migrations.AddIndex(
            model_name='netsuiteconnection',
            index=models.Index(fields=['company', 'is_active'], name='ns_conn_co_active_idx'),
        ),
        migrations.AddField(
            model_name='employeeconnection',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='netsuite.netsuiteconnection'),
        ),
        migrations.AddField(
            model_name='employeeconnection',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_netsuite_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeconnection',
            index=models.Index(fields=['employee'], name='emp_conn_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeconnection',
            index=models.Index(fields=['connection'], name='emp_conn_conn_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeconnection',
            constraint=models.UniqueConstraint(fields=('employee', 'connection'), name='unique_employee_connection'),
        ),
    ]
