# Generated by Django 6.0.7 on 2026-08-17 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0007_employeeconnection_netsuiteconnection_company_and_more'),
        ('ocr', '0006_remove_ocrbatch_batch_ocrupload_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetSuiteOCRPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(default='vendorBill', max_length=80)),
                ('netsuite_record_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('error', 'Error')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_postings', to='netsuite.netsuiteconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsuite_ocr_postings', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_postings', to='ocr.ocrdocument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_postings', to='ocr.ocrdocumentversion')),
            ],
            options={
                'db_table': 'netsuite_ocr_posting',
                'indexes': [models.Index(fields=['connection', 'status'], name='ns_post_conn_status_idx'), models.Index(fields=['netsuite_record_id'], name='ns_post_record_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='unique_ocr_netsuite_posting')],
            },
        ),
        migrations.CreateModel(
            name='NetSuiteReferenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=80)),
                ('internal_id', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('search_name', models.CharField(blank=True, default='', max_length=500)),
                ('item_type', models.CharField(blank=True, max_length=80, null=True)),
                ('is_inactive', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_records', to='netsuite.netsuiteconnection')),
            ],
            options={
                'db_table': 'netsuite_reference_record',
                'indexes': [models.Index(fields=['connection', 'record_type', 'search_name'], name='ns_ref_conn_type_name_idx'), models.Index(fields=['connection', 'record_type', 'external_id'], name='ns_ref_conn_type_ext_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'record_type', 'internal_id'), name='unique_ns_reference_record')],
            },
        ),
    ]
