# Generated by Django 6.0.7 on 2026-08-21 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0008_netsuiteocrposting_netsuitereferencerecord'),
        ('tenancy', '0011_add_company_industry_size_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetSuiteCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('body', 'Body'), ('column', 'Column / Item Sublist')], max_length=20)),
                ('field_label', models.CharField(max_length=255)),
                ('field_id', models.CharField(max_length=100)),
                ('datatype', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('currency', 'Currency')], max_length=20)),
                ('source_field_key', models.CharField(max_length=100)),
                ('source_field_label', models.CharField(max_length=255)),
                ('netsuite_field_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_custom_fields', to='tenancy.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_custom_fields', to='netsuite.netsuiteconnection')),
            ],
            options={
                'db_table': 'netsuite_custom_field',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'connection', 'record_type'], name='ns_cf_conn_idx'), models.Index(fields=['source_field_key'], name='ns_cf_src_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'connection', 'record_type', 'scope', 'source_field_key'), name='unique_ns_custom_field_per_context')],
            },
        ),
    ]
