# Generated by Django 6.0.7 on 2026-08-24 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0009_add_field_mapping_validation_models'),
        ('tenancy', '0011_add_company_industry_size_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='netsuiteconnection',
            name='unique_user_netsuite_account',
        ),
        migrations.AlterField(
            model_name='netsuiteconnection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_connections', to='tenancy.company'),
        ),
        migrations.AddConstraint(
            model_name='netsuiteconnection',
            constraint=models.UniqueConstraint(fields=('company', 'netsuite_account_id'), name='unique_company_netsuite_account'),
        ),
    ]
