# Generated by Django 6.0.7 on 2026-08-25 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0010_remove_netsuiteconnection_unique_user_netsuite_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetSuiteFieldCatalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(default='vendorBill', max_length=80)),
                ('body_fields', models.JSONField(blank=True, default=list)),
                ('line_fields', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_hash', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_catalogues', to='netsuite.netsuiteconnection')),
            ],
            options={
                'db_table': 'netsuite_field_catalogue',
                'indexes': [models.Index(fields=['connection', 'record_type'], name='ns_field_cat_conn_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'record_type'), name='unique_ns_field_catalogue_connection_record')],
            },
        ),
    ]
