# Generated by Django 6.0.7 on 2026-08-25 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0011_netsuitefieldcatalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetSuiteUserConnectionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='netsuite.netsuiteconnection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='netsuite_connection_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'netsuite_user_connection_preference',
            },
        ),
    ]
