# Generated by Django 6.0.7 on 2026-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0012_netsuiteuserconnectionpreference'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='netsuiteconnectionauditlog',
            name='ns_audit_user_recent_idx',
        ),
        migrations.DeleteModel(
            name='NetSuiteConnectionAuditLog',
        ),
    ]
