# Generated by Django 6.0.7 on 2026-09-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0013_remove_netsuiteconnectionauditlog_ns_audit_user_recent_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetSuiteUserConnectionPreference',
        ),
    ]
