# Generated by Django 6.0.7 on 2026-08-04 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_alter_module_options_companymodule_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_batches', to='tenancy.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='invoices/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='invoice.invoicebatch')),
            ],
            options={
                'db_table': 'invoice_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_json', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='invoice.invoicefile')),
            ],
            options={
                'db_table': 'extracted_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicebatch',
            index=models.Index(fields=['company', '-created_at'], name='invoice_batch_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefile',
            index=models.Index(fields=['batch', '-created_at'], name='invoice_file_batch_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedinvoice',
            index=models.Index(fields=['invoice_file'], name='extracted_invoice_file_idx'),
        ),
    ]
