# Generated by Django 6.0.7 on 2026-08-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicebatch',
            new_name='inv_batch_company_recent_idx',
            old_name='invoice_batch_company_recent_idx',
        ),
    ]
