# Generated by Django 6.0.7 on 2026-08-04 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_invoice_batch_company_recent_idx_inv_batch_company_recent_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNetSuiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_field', models.CharField(max_length=100, unique=True)),
                ('netsuite_field', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_netsuite_mapping',
                'ordering': ['invoice_field'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_review_history',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddField(
            model_name='extractedinvoice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedinvoice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicefile',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('READY_FOR_NETSUITE', 'Ready for NetSuite'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoicefile',
            index=models.Index(fields=['status'], name='invoice_file_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenetsuitemapping',
            index=models.Index(fields=['is_active'], name='inv_ns_mapping_active_idx'),
        ),
        migrations.AddField(
            model_name='invoicereviewhistory',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_review_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereviewhistory',
            name='extracted_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='invoice.extractedinvoice'),
        ),
        migrations.AddIndex(
            model_name='invoicereviewhistory',
            index=models.Index(fields=['extracted_invoice', '-edited_at'], name='inv_review_history_idx'),
        ),
    ]
