# Generated by Django 6.0.7 on 2026-09-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoicenetsuitemapping_invoicereviewhistory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='extractedinvoice',
            name='extracted_invoice_file_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicenetsuitemapping',
            name='inv_ns_mapping_active_idx',
        ),
        migrations.DeleteModel(
            name='InvoiceNetSuiteMapping',
        ),
        migrations.RemoveIndex(
            model_name='invoicereviewhistory',
            name='inv_review_history_idx',
        ),
        migrations.RemoveField(
            model_name='invoicereviewhistory',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='invoicereviewhistory',
            name='extracted_invoice',
        ),
        migrations.DeleteModel(
            name='ExtractedInvoice',
        ),
        migrations.DeleteModel(
            name='InvoiceReviewHistory',
        ),
    ]
