# Generated by Django 6.0.7 on 2026-08-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_active_idx',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, default='', editable=False, help_text='Unique immutable company identifier.', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='AGSuiteTech', max_length=255),
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
