# Generated by Django 5.2.16 on 2026-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_alter_module_options_companymodule_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='last_usage_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymodule',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
