# Generated by Django 6.0.7 on 2026-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_companymodule_last_usage_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_phone_country_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
