# Generated by Django 6.0.7 on 2026-08-19 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_company_unique_company_name_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_modules', to='tenancy.company'),
        ),
        migrations.CreateModel(
            name='CompanyDeletionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id_snapshot', models.UUIDField(db_index=True, help_text='ID of the deleted company captured before permanent deletion.')),
                ('company_name', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=50)),
                ('soft_deleted_at', models.DateTimeField()),
                ('permanently_deleted_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_deletions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_deletion_history',
                'ordering': ['-permanently_deleted_at'],
                'indexes': [models.Index(fields=['company_id_snapshot'], name='company_del_history_company_idx'), models.Index(fields=['permanently_deleted_at'], name='company_del_history_deleted_idx')],
            },
        ),
    ]
