# Generated by Django 6.0.7 on 2026-08-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_alter_companymodule_company_companydeletionhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companydeletionhistory',
            new_name='cdh_company_id_idx',
            old_name='company_del_history_company_idx',
        ),
        migrations.RenameIndex(
            model_name='companydeletionhistory',
            new_name='cdh_deleted_at_idx',
            old_name='company_del_history_deleted_idx',
        ),
    ]
