# Generated by Django 6.0.7 on 2026-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_rename_company_del_history_company_idx_cdh_company_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='suspension_reason',
            field=models.CharField(choices=[('NONE', 'None'), ('MANUAL', 'Manual Suspension'), ('PLAN', 'Subscription Issue'), ('DELETED', 'Soft Deleted')], db_index=True, default='NONE', max_length=20),
        ),
    ]
