# Generated by Django 6.0.7 on 2026-09-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_remove_plan_enabled_models'),
        ('tenancy', '0011_add_company_industry_size_city'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companymodule',
            name='unique_company_module',
        ),
        migrations.RemoveField(
            model_name='companymodule',
            name='activated_by',
        ),
        migrations.RemoveField(
            model_name='companymodule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companymodule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companymodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='companymodule',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='CompanyModule',
        ),
    ]
