# Generated by Django 6.0.7 on 2026-09-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_company_currency_company_date_format_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
