# Generated by Django 6.0.7 on 2026-09-15 18:03

import django.db.models.deletion
from django.db import migrations, models


def migrate_current_company_plans(apps, schema_editor):
    try:
        Company = apps.get_model("tenancy", "Company")
        CompanyPlan = apps.get_model("superadmin", "CompanyPlan")
    except LookupError:
        return

    # Only migrate the current ACTIVE/TRIAL assignment for each company.
    # If multiple current rows somehow exist, take the newest one.
    company_plans = (
        CompanyPlan.objects
        .filter(status__in=["ACTIVE", "TRIAL"])
        .select_related("plan")
        .order_by("company_id", "-start_date", "-id")
    )

    processed_companies = set()

    for company_plan in company_plans:
        company_id = company_plan.company_id

        # One current plan per company.
        if company_id in processed_companies:
            continue

        Company.objects.filter(pk=company_id).update(
            plan_id=company_plan.plan_id,
            plan_start_date=company_plan.start_date,
            plan_end_date=company_plan.end_date,
        )

        processed_companies.add(company_id)


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0007_delete_supportsession"),
        ("tenancy", "0014_delete_companysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned subscription plan.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="superadmin.plan",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="plan_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date of the current subscription plan.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="plan_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date of the current subscription plan.",
                null=True,
            ),
        ),

        migrations.RunPython(
            migrate_current_company_plans,
            migrations.RunPython.noop,
        ),
    ]